services:
  db:
    image: mysql:8.4
    restart: no
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "test_db:/var/lib/mysql"

volumes:
  test_db:
